;; This logfile was generated automatically by `xindy'
;; at 28.12.2013  08:01:43
;; Indexstyle: "/tmp/fgtXGgwP30", Rawindex: "/tmp/oMmi2RyS0P", Output: "Tesis.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "œ" -> "D"
Letter-group: "´œ" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´œ" -> "L"
